<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="prop_r" value="0.05"/>
  <xacro:property name="prop_l" value="0.035"/>

  <xacro:macro name="thruster" params="thruster_id *origin">
    <link name="${ns}/thruster${thruster_id}">
      <visual>
        <origin xyz="0.10 0.10 0" rpy="${pi/2} ${pi} 0"/>
        <geometry>
          <!-- cylinder length="${prop_l}" radius="${prop_r}"/ -->
          <mesh filename="file://$(find bur_gz)/meshes/Impeller.STL" scale="0.0007 0.0007 0.0007"/>
        </geometry>

        <xacro:if value="${thruster_id in [1,2,3,4]}">
          <material name="yellow"/>
        </xacro:if>
        <xacro:if value="${thruster_id in [5,6,7,8]}">
          <material name="red"/>
        </xacro:if>
      </visual>

      <collision>
        <origin xyz="0.10 0.10 0" rpy="${pi/2} ${pi} 0"/>
        <geometry>
          <!-- cylinder length="${prop_l}" radius="${prop_r}"/ -->
          <mesh filename="file://$(find bur_gz)/meshes/Impeller.STL" scale="0.0007 0.0007 0.0007"/>
        </geometry>
      </collision>

      <inertial>
        <!-- thruster axis is X -->
        <origin xyz="${prop_l/2} 0 0" rpy="0 0 0" />
        <mass value="${prop_mass}" />
        <inertia  izz="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" ixy="0.0"  ixz="0.0"
                  iyy="${prop_mass*prop_r*prop_r / 4  + prop_mass*prop_l*prop_l / 12}" iyz="0.0" ixx="${prop_mass*prop_r*prop_r / 2}" />
      </inertial>
    </link>

    <!-- Joint between thruster link and vehicle base link -->
    <joint name="thruster${thruster_id}" type="continuous">
      <xacro:insert_block name="origin" />
      <axis xyz="0 0 1" />
      <parent link="${ns}/base_link" />
      <child link="${ns}/thruster${thruster_id}" />
    </joint>

    <!-- ignition topic is /model/{ns}/joint/{joint_name}/cmd_pos -->
    <gazebo>
      <plugin
          filename="ignition-gazebo-thruster-system"
          name="ignition::gazebo::systems::Thruster">
        <namespace>${ns}</namespace>
        <joint_name>thruster${thruster_id}</joint_name>
        <topic>thruster${thruster_id}/cmd</topic>
        <thrust_coefficient>0.011</thrust_coefficient>
        <fluid_density>${density}</fluid_density>
        <propeller_diameter>${2*prop_r}</propeller_diameter>
        <velocity_control>true</velocity_control>
        <use_angvel_cmd>false</use_angvel_cmd>
        <max_thrust_cmd>40</max_thrust_cmd>
        <min_thrust_cmd>-40</min_thrust_cmd>
      </plugin>
    </gazebo>
  </xacro:macro>

</robot>
